apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: e-commerce
type: opaque
stringData:
    MYSQL_ROOT_PASSWORD: RootPass@123
    MYSQL_DATABASE: ecommjava
    MYSQL_USER: ecommerce_user
    MYSQL_PASSWORD: Ecomm@123
